// packages/angular/src/index.ts
import { Directive, ElementRef, Input, OnInit, OnDestroy } from '@angular/core';
import ImgFit from '@danilo.riedel/img-fit';

@Directive({
  selector: '[imgFit]'
})
export class ImgFitDirective implements OnInit, OnDestroy {
  @Input('imgFit') src: string = '';
  @Input() imgFitParams: string = '';
  @Input() imgFitOptions: object = {};

  constructor(private el: ElementRef<HTMLImageElement>) {}

  ngOnInit(): void {
    const element = this.el.nativeElement;
    if (!element) {
      return;
    }

    element.setAttribute('data-img-fit', this.src);
    if (this.imgFitParams) {
      element.setAttribute('data-img-fit-params', this.imgFitParams);
    }

    ImgFit.watch(element, this.imgFitOptions);
  }

  ngOnDestroy(): void {
    ImgFit.unwatch(this.el.nativeElement);
  }
}

export default ImgFitDirective;

// packages/react/src/index.js
import React, { useEffect, useRef } from 'react';
import ImgFitCore from '@danilo.riedel/img-fit';

/**
 * React component that renders an optimized <img> for img-fwd.
 *
 * @param {object} props
 * @param {string} props.src
 * @param {string} [props.alt]
 * @param {string} [props.params]
 * @param {object} [props.options]
 */
export function ImgFit({ src, alt = '', params = '', options = {}, ...rest }) {
  const imgRef = useRef(null);

  useEffect(() => {
    const element = imgRef.current;
    if (!element) {
      return undefined;
    }

    element.setAttribute('data-img-fit', src);
    if (params) {
      element.setAttribute('data-img-fit-params', params);
    } else {
      element.removeAttribute('data-img-fit-params');
    }

    ImgFitCore.watch(element, options);

    return () => {
      ImgFitCore.unwatch(element);
    };
  }, [src, params, JSON.stringify(options)]);

  return React.createElement('img', {
    ref: imgRef,
    src,
    alt,
    'data-img-fit': src,
    'data-img-fit-params': params || undefined,
    ...rest
  });
}

export default ImgFit;
